// Action types

export const GET_SIGNUP_REQUEST = 'GET_SIGNUP_REQUEST';
export const GET_SIGNUP_SUCCESS = 'GET_SIGNUP_SUCCESS';
export const GET_SIGNUP_FAILURE = 'GET_SIGNUP_FAILURE';

export const GET_VERIFY_REQUEST = 'GET_VERIFY_REQUEST';
export const GET_VERIFY_SUCCESS = 'GET_VERIFY_SUCCESS';
export const GET_VERIFY_FAILURE = 'GET_VERIFY_FAILURE';

export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

export const GET_LOGOUT_REQUEST = 'GET_LOGOUT_REQUEST';
export const GET_LOGOUT_SUCCESS = 'GET_LOGOUT_SUCCESS';
export const GET_LOGOUT_FAILURE = 'GET_LOGOUT_FAILURE';

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE';

export const GET_CREATE_REQUEST = 'GET_CREATE_REQUEST';
export const GET_CREATE_SUCCESS = 'GET_CREATE_SUCCESS';
export const GET_CREATE_FAILURE = 'GET_CREATE_FAILURE';

export const GET_EVENT_IMAGE_REQUEST = 'GET_EVENT_IMAGE_REQUEST';
export const GET_EVENT_IMAGE_SUCCESS = 'GET_EVENT_IMAGE_SUCCESS';
export const GET_EVENT_IMAGE_FAILURE = 'GET_EVENT_IMAGE_FAILURE';

export const GET_CREATE_COMMENT_REQUEST = 'GET_CREATE_COMMENT_REQUEST';
export const GET_CREATE_COMMENT_SUCCESS = 'GET_CREATE_COMMENT_SUCCESS';
export const GET_CREATE_COMMENT_FAILURE = 'GET_CREATE_COMMENT_FAILURE';

export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';

export const GET_ENROLL_REQUEST = 'GET_ENROLL_REQUEST';
export const GET_ENROLL_SUCCESS = 'GET_ENROLL_SUCCESS';
export const GET_ENROLL_FAILURE = 'GET_ENROLL_FAILURE';

export const GET_UNENROLL_REQUEST = 'GET_UNENROLL_REQUEST';
export const GET_UNENROLL_SUCCESS = 'GET_UNENROLL_SUCCESS';
export const GET_UNENROLL_FAILURE = 'GET_UNENROLL_FAILURE';

export const GET_LOG_REQUEST = 'GET_LOG_REQUEST';
export const GET_LOG_SUCCESS = 'GET_LOG_SUCCESS';
export const GET_LOG_FAILURE = 'GET_LOG_FAILURE';

export const GET_ATTENDEES_REQUEST = 'GET_ATTENDEES_REQUEST';
export const GET_ATTENDEES_SUCCESS = 'GET_ATTENDEES_SUCCESS';
export const GET_ATTENDEES_FAILURE = 'GET_ATTENDEES_FAILURE';

export const GET_VOTE_REQUEST = 'GET_VOTE_REQUEST';
export const GET_VOTE_SUCCESS = 'GET_VOTE_SUCCESS';
export const GET_VOTE_FAILURE = 'GET_VOTE_FAILURE';