// Action types

export const GET_CREATE_USER_REQUEST = 'GET_CREATE_USER_REQUEST';
export const GET_CREATE_USER_SUCCESS = 'GET_CREATE_USER_SUCCESS';
export const GET_CREATE_USER_FAILURE = 'GET_CREATE_USER_FAILURE';

export const GET_VERIFY_SIGNUP_CODE_REQUEST = 'GET_VERIFY_SIGNUP_CODE_REQUEST';
export const GET_VERIFY_SIGNUP_CODE_SUCCESS = 'GET_VERIFY_SIGNUP_CODE_SUCCESS';
export const GET_VERIFY_SIGNUP_CODE_FAILURE = 'GET_VERIFY_SIGNUP_CODE_FAILURE';

export const GET_FORGOT_PASSWORD_REQUEST = 'GET_FORGOT_PASSWORD_REQUEST';
export const GET_FORGOT_PASSWORD_SUCCESS = 'GET_FORGOT_PASSWORD_SUCCESS';
export const GET_FORGOT_PASSWORD_FAILURE = 'GET_FORGOT_PASSWORD_FAILURE';

export const GET_RESET_PASSWORD_REQUEST = 'GET_RESET_PASSWORD_REQUEST';
export const GET_RESET_PASSWORD_SUCCESS = 'GET_RESET_PASSWORD_SUCCESS';
export const GET_RESET_PASSWORD_FAILURE = 'GET_RESET_PASSWORD_FAILURE';

export const GET_VERIFY_FORGOT_PASSWORD_CODE_REQUEST = 'GET_VERIFY_FORGOT_PASSWORD_CODE_REQUEST';
export const GET_VERIFY_FORGOT_PASSWORD_CODE_SUCCESS = 'GET_VERIFY_FORGOT_PASSWORD_CODE_SUCCESS';
export const GET_VERIFY_FORGOT_PASSWORD_CODE_FAILURE = 'GET_VERIFY_FORGOT_PASSWORD_CODE_FAILURE';

export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

export const GET_LOGOUT_REQUEST = 'GET_LOGOUT_REQUEST';
export const GET_LOGOUT_SUCCESS = 'GET_LOGOUT_SUCCESS';
export const GET_LOGOUT_FAILURE = 'GET_LOGOUT_FAILURE';

export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE';

export const GET_CREATE_EVENT_REQUEST = 'GET_CREATE_EVENT_REQUEST';
export const GET_CREATE_EVENT_SUCCESS = 'GET_CREATE_EVENT_SUCCESS';
export const GET_CREATE_EVENT_FAILURE = 'GET_CREATE_EVENT_FAILURE';

export const GET_UPDATE_EVENT_REQUEST = 'GET_UPDATE_EVENT_REQUEST';
export const GET_UPDATE_EVENT_SUCCESS = 'GET_UPDATE_EVENT_SUCCESS';
export const GET_UPDATE_EVENT_FAILURE = 'GET_UPDATE_EVENT_FAILURE';

export const GET_EVENT_IMAGE_REQUEST = 'GET_EVENT_IMAGE_REQUEST';
export const GET_EVENT_IMAGE_SUCCESS = 'GET_EVENT_IMAGE_SUCCESS';
export const GET_EVENT_IMAGE_FAILURE = 'GET_EVENT_IMAGE_FAILURE';

export const GET_DELETE_EVENT_REQUEST = 'GET_DELETE_EVENT_REQUEST';
export const GET_DELETE_EVENT_SUCCESS = 'GET_DELETE_EVENT_SUCCESS';
export const GET_DELETE_EVENT_FAILURE = 'GET_DELETE_EVENT_FAILURE';

export const GET_UPDATE_EVENT_PICS_REQUEST = 'GET_UPDATE_EVENT_PICS_REQUEST';
export const GET_UPDATE_EVENT_PICS_SUCCESS = 'GET_UPDATE_EVENT_PICS_SUCCESS';
export const GET_UPDATE_EVENT_PICS_FAILURE = 'GET_UPDATE_EVENT_PICS_FAILURE';

export const GET_CREATE_COMMENT_REQUEST = 'GET_CREATE_COMMENT_REQUEST';
export const GET_CREATE_COMMENT_SUCCESS = 'GET_CREATE_COMMENT_SUCCESS';
export const GET_CREATE_COMMENT_FAILURE = 'GET_CREATE_COMMENT_FAILURE';

export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';

export const GET_ENROLL_REQUEST = 'GET_ENROLL_REQUEST';
export const GET_ENROLL_SUCCESS = 'GET_ENROLL_SUCCESS';
export const GET_ENROLL_FAILURE = 'GET_ENROLL_FAILURE';

export const GET_UNENROLL_REQUEST = 'GET_UNENROLL_REQUEST';
export const GET_UNENROLL_SUCCESS = 'GET_UNENROLL_SUCCESS';
export const GET_UNENROLL_FAILURE = 'GET_UNENROLL_FAILURE';

export const GET_LOG_REQUEST = 'GET_LOG_REQUEST';
export const GET_LOG_SUCCESS = 'GET_LOG_SUCCESS';
export const GET_LOG_FAILURE = 'GET_LOG_FAILURE';

export const GET_VOTE_REQUEST = 'GET_VOTE_REQUEST';
export const GET_VOTE_SUCCESS = 'GET_VOTE_SUCCESS';
export const GET_VOTE_FAILURE = 'GET_VOTE_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_UPDATE_USER_REQUEST = 'GET_UPDATE_USER_REQUEST';
export const GET_UPDATE_USER_SUCCESS = 'GET_UPDATE_USER_SUCCESS';
export const GET_UPDATE_USER_FAILURE = 'GET_UPDATE_USER_FAILURE';